CREATE PROC sp_KiemTraMaVT
@MA NCHAR(4)
AS
BEGIN
	IF EXISTS(SELECT MAVT FROM Vattu WHERE MAVT= @MA)
		RETURN 1;
	ELSE IF EXISTS(SELECT MAVT FROM LINK1.QLVT_DATHANG.DBO.Vattu VT WHERE VT.MAVT=@MA)
		RETURN 1;
	RETURN 0;
END
